### ISSUE TITLE
Obciąć zera po kropce

### ISSUE THREAD

**Issue by Werndl** [Werndl/raport-generator#33]
Np. zamiast 72.0 godzin to 72

**Comment by Werndl** [comment]
Nie widzę by było zrobione.

**Comment by nodza94** [comment]
Kroki gdzie jest issue? U mnie ok
Np. raport 1 -> 2018
Alfabetyczna lista pracowników za rok 2018
Lp         Pracownik                      Godziny [h]
1          Damian Kowal                   194.7     
2          Katarzyna Mara                 135       
3          Marta Bolas                    72        
Suma:                                     401.7
