### ISSUE TITLE
[Raport 1] Brak walidacji przy nieistniejącym katalogu "rok"

### ISSUE THREAD

**Issue by Werndl** [Werndl/raport-generator#36]
**Aktualny rezultat:**
Nie dostaję komunikatu błędu, tylko generuje się pusty raport.

**Oczekiwany rezultat:**
Komunikat: "Projektu nie prowadzono w XXXX roku!"
oraz
"Raport jest pusty - plik nie zostanie wygenerowany."

**Kroki reprodukcji:**
- Wybieram opcję nr 1
- Wpisuję rok, którego nie ma w katalogu
- Chcę wyeksportować raport do pliku

**Comment by Werndl** [comment]
No prawie dobrze. Ale dodaj to info "Raport jest pusty - plik nie zostanie wygenerowany." jeszcze.

**Comment by nodza94** [comment]
Walidacja powoduje, że użytkownik w ogóle nie dostanie możliwości generowania Excela, więc nie ma sensu dodawanie tego komentarza - reszta raportów działa tak samo. Linjka została usunięta z kodu
