### ISSUE TITLE
Nieprawidłowa treść komunikatu

### ISSUE THREAD

**Issue by Werndl** [Werndl/raport-generator#38]
**Aktualny rezultat:**
Czy chcesz wygenerować raport do pliku Excel?
WPISZ: 1 jeśli TAK, wciśnij inny klawisz jeśli NIE: 
1
Prosze podac nazwe raportu: ee
PODANA SCIEŻKA JEST BŁĘDNA. Powrót do Menu

**Oczekiwany rezultat:**
Czy chcesz wygenerować raport do pliku Excel?
WPISZ: 1 jeśli TAK, wciśnij inny klawisz jeśli NIE: 
1
Proszę podać scieżkę do zapisania pliku: ee
PODANA SCIEŻKA JEST BŁĘDNA. Powrót do Menu

**Comment by Werndl** [comment]
No jest prawie dobrze. Ja bym tu jeszcze zrobiła walidację zaraz po pytaniu "Podaj rok, dla którego chcesz wygenerować raport". Jeśli użytkownik poda nieprawidłowy rok to nie powinno go puścić dalej.

**Comment by Werndl** [comment]
No nie jest dobrze:
Czy chcesz wygenerować raport do pliku Excel?
WPISZ: 1 jeśli TAK, wciśnij inny klawisz jeśli NIE: 
1
PODANA ŚCIEŻKA JEST BŁĘDNA. Powrót do Menu

Ma być:
Czy chcesz wygenerować raport do pliku Excel?
WPISZ: 1 jeśli TAK, wciśnij inny klawisz jeśli NIE:
1
Proszę podać scieżkę do zapisania pliku: ...

**Comment by nodza94** [comment]
fixed
