### ISSUE TITLE
Uspójnić komunikaty (polskie znaki)

### ISSUE THREAD

**Issue by Werndl** [Werndl/raport-generator#41]
**Aktualny rezultat:**

Proszę podać scieżkę katalogu danych:

PODANA SCIEŻKA JEST BŁĘDNA

Podaj imie i nazwisko osoby, dla której chcesz wygenerować raport

**Oczekiwany rezultat:**

Proszę podać ścieżkę katalogu danych:

PODANA ŚCIEŻKA JEST BŁĘDNA

Podaj imię i nazwisko osoby, dla której chcesz wygenerować raport

**Comment by Werndl** [comment]
Jeszcze do poprawy jest "Proszę podać scieżkę do zapisania pliku" gdy pyta o ścieżkę do zapisania excela.

**Comment by nodza94** [comment]
fixed
