### ISSUE TITLE
[Raport 3] Brak walidacji przy nieistniejącym katalogu "rok"

### ISSUE THREAD

**Issue by Werndl** [Werndl/raport-generator#42]
**Aktualny rezultat:**
Podaj imie i nazwisko osoby, dla której chcesz wygenerować raport: ...

**Oczekiwany rezultat:**
Komunikat: "Projektu nie prowadzono w XXXX roku!"

**Kroki reprodukcji:**
Wpisz wybraną opcję: 3
Generowanie raportu numer: 3
++++++++++++++++++++++++++++++++++++++++++
Podaj rok, dla którego chcesz wygenerować raport: 1010

**Comment by Werndl** [comment]
No jest prawie dobrze. Ja bym tu jeszcze zrobiła walidację zaraz po pytaniu "Podaj rok, dla którego chcesz wygenerować raport". Jeśli użytkownik poda nieprawidłowy rok to nie powinno go puścić dalej.

**Comment by nodza94** [comment]
ja bym zostawiła, tak jak jest. Bo od razu dostanie też komunikat, że wybrany pracownik jest źle. Potraktujmy to jak funkcje Raport3(year,EE) i równoczesne wprowadzanie parametrów
