### ISSUE TITLE
Nieprawidłowa walidacja ścieżki do zapisania raportu

### ISSUE THREAD

**Issue by Werndl** [Werndl/raport-generator#50]
**Aktualny rezultat:**
`PODANA ŚCIEŻKA JEST BŁĘDNA. Powrót do Menu`
**Oczekiwany rezulatat:**
`PODANA ŚCIEŻKA JEST BŁĘDNA. WPISZ: 1 jeśli chcesz spróbować jeszcze raz lub wciśnij inny klawisz jeśli chcesz wrócić do menu.`
**Kroki reprodukcji:**
1. Odpalanie programu
2. Wybranie opcji nr 1
3. `Czy chcesz wygenerować raport do pliku Excel?
WPISZ: 1 jeśli TAK, wciśnij inny klawisz jeśli NIE: 
1
Proszę podać scieżkę do zapisania pliku:ffghtfh`

**Comment by nodza94** [comment]
Nie widzę tej opcji jako aktualny rezultat, to było bardzo stare ustawienie

**Comment by Werndl** [comment]
Pomylliło mi się. Odwrotnie mi chodziło xD. Już poprawiam.

**Comment by nodza94** [comment]
fixed
